### PR TITLE
Add support for custom command dispatchers

### PR DESCRIPTION
**Pull request by soywiz**
I have added support for hooking custom commands. The idea here is that people using libftpvita can support custom commands in their code, allowing some kind of new applications.

I have created a psvita organizer to be able to upload vita applications directly from the computer:
https://github.com/soywiz/vitaorganizer

And my current objective is to be able to support this:
https://github.com/TheOfficialFloW/VitaShell/issues/38

After uploading be able to signal VitaShell, so it can start promoting the just uploaded app in just one step.

So a the idea is to create a command like "PROM":
And then with ftpvita_ext_add_custom_command, being able to execute code related to promoting apps.

But another idea could be to create a command like "TREESIZE" to be able to get the size of a directory tree directly, for example to get the size of a game faster.

### CODE REVIEW

**Comment by xerpi** [comment]
That's a good idea, but I don't think ClientInfo should be opaque, otherwise it won't be possible to use ClientInfo's attributes from the cmd_dispatch_func callback.
Maybe we should export client_send_data_msg too.
Also I think it would be a good idea to rename ClientInfo to ftpvita_client_info/ftpvita_client_info_t.

**Comment by soywiz** [comment]
That's right. I wanted to avoid exposing it to avoid breaking code if you decide to change that structure. I could also create a couple of functions to get relevant information.

But I will expose the structure as you said if you are not against it.

**Comment by soywiz** [comment]
Done. Check if that was what you wanted

**Comment by xerpi** [comment]
Yeah looks good :)

**Pull request merged**
